name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint

    - name: Analysing the code with pylint (min score 7.0)
      run: |
          export DJANGO_SETTINGS_MODULE=project.settings
          export PYTHONPATH=.
          echo "Running Pylint..."
          pylint --disable=W $(cat pyfiles.txt) --score=y --exit-zero | tee pylint.log
          SCORE=$(tail -n 2 pylint.log | grep 'Your code has been rated at' | awk '{print $7}' | cut -d/ -f1)
          echo "Pylint score: $SCORE"
    
