site_name: GenT
site_name: GenT
site_description: Documentação oficial do projeto
site_author: Equipe Sanum
repo_url: https://github.com/mdsreq-fga-unb/REQ-2025.2-T01-ST-APP
repo_name: REQ-2025.2-T01-ST-APP

theme:
  name: material
  language: pt-BR
  favicon: docs/assets/logounb.svg
  logo: 
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: purple
      accent: brown
      toggle:
        icon: material/toggle-switch-off-outline
        name: Modo escuro
    - scheme: slate
      primary: purple
      accent: brown
      toggle:
        icon: material/toggle-switch
        name: Modo claro
  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - repo.icon

nav:
  - Início: index.md
  - Entregas: 
    - Unidade 1: pages/entregas/entrega1.md
    - Unidade 2: pages/entregas/entrega2.md
  - Visão do Produto e Projeto:
      - Cenario atual do cliente e do negócio: pages/visaoDoProduto/cenarioAtual.md
      - Solução Proposta: pages/visaoDoProduto/solucao.md
      - Estratégias de Engenharia de Software: pages/visaoDoProduto/estrategias.md
      - Cronogramas e Entregas: pages/visaoDoProduto/cronogramasEntregas.md
      - Interação da Equipe com o Cliente: pages/visaoDoProduto/interacaooEquipeCliente.md
      - Lições Aprendidas: pages/visaoDoProduto/licoesAprendidas.md
  - Backlog:
      - Requisitos: pages/backlog/requisitos.md
      - Backlog do Produto: pages/backlog/backlog.md