"""Adiciona coluna nome ao User

Revision ID: 1279574c7827
Revises: 980ebffa0925
Create Date: 2025-11-05 01:26:10.269432

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1279574c7827"
down_revision: Union[str, Sequence[str], None] = "980ebffa0925"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_usuarios_nome"), "usuarios", ["nome"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usuarios_nome"), table_name="usuarios")
    # ### end Alembic commands ###
