"""Adiciona coluna data_resposta

Revision ID: 2ef0163fafa4
Revises: e63cf2085a56
Create Date: 2025-12-01 20:13:48.206619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef0163fafa4'
down_revision: Union[str, Sequence[str], None] = 'e63cf2085a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pesquisa_sociodemografica_usuario_id', table_name='pesquisa_sociodemografica')
    op.create_unique_constraint(None, 'pesquisa_sociodemografica', ['usuario_id'])
    op.drop_index('ix_usuarios_nome', table_name='usuarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_usuarios_nome', 'usuarios', ['nome'], unique=False)
    op.drop_constraint(None, 'pesquisa_sociodemografica', type_='unique')
    op.create_index('ix_pesquisa_sociodemografica_usuario_id', 'pesquisa_sociodemografica', ['usuario_id'], unique=False)
    # ### end Alembic commands ###
