"""Cria tabela Empresa e liga a Usuarios e Perguntas

Revision ID: 43566a550cf9
Revises: ad1b7281bd54
Create Date: 2025-11-10 16:00:51.540579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43566a550cf9'
down_revision: Union[str, Sequence[str], None] = 'ad1b7281bd54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_index(op.f('ix_empresas_nome'), 'empresas', ['nome'], unique=True)
    op.create_table('perguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perguntas_id'), 'perguntas', ['id'], unique=False)
    op.create_table('respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=True),
    sa.Column('votos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pergunta_id'], ['perguntas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_respostas_id'), 'respostas', ['id'], unique=False)
    op.add_column('usuarios', sa.Column('empresa_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'empresas', ['empresa_id'], ['id'])
    op.drop_column('usuarios', 'empresa')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('empresa', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'empresa_id')
    op.drop_index(op.f('ix_respostas_id'), table_name='respostas')
    op.drop_table('respostas')
    op.drop_index(op.f('ix_perguntas_id'), table_name='perguntas')
    op.drop_table('perguntas')
    op.drop_index(op.f('ix_empresas_nome'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
