"""Rename is_activate to is_active

Revision ID: 45b1d490ac3b
Revises: 1279574c7827
Create Date: 2025-11-05 17:07:13.649759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b1d490ac3b'
down_revision: Union[str, Sequence[str], None] = '1279574c7827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('usuarios', 'is_activate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('is_activate', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('usuarios', 'is_active')
    # ### end Alembic commands ###
