"""Muda para Likert scale e remove tabela OpcoesDeResposta

Revision ID: 9caa4c12924b
Revises: e6461ea630f3
Create Date: 2025-11-11 13:53:45.553234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9caa4c12924b'
down_revision: Union[str, Sequence[str], None] = 'e6461ea630f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_opcoes_de_resposta_id', table_name='opcoes_de_resposta')
    op.add_column('respostas_do_usuario', sa.Column('voto_valor', sa.Integer(), nullable=False))
    op.drop_constraint('respostas_do_usuario_opcao_id_fkey', 'respostas_do_usuario', type_='foreignkey')
    op.drop_column('respostas_do_usuario', 'opcao_id')
    op.drop_table('opcoes_de_resposta')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opcoes_de_resposta',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pergunta_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pergunta_id'], ['perguntas.id'], name='opcoes_de_resposta_pergunta_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='opcoes_de_resposta_pkey')
    )
    op.add_column('respostas_do_usuario', sa.Column('opcao_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('respostas_do_usuario_opcao_id_fkey', 'respostas_do_usuario', 'opcoes_de_resposta', ['opcao_id'], ['id'])
    op.drop_column('respostas_do_usuario', 'voto_valor')
    op.create_index('ix_opcoes_de_resposta_id', 'opcoes_de_resposta', ['id'], unique=False)
    # ### end Alembic commands ###
