"""Adiciona data_resposta e pesquisa sociodemografica

Revision ID: 9e963e794566
Revises: d9fe8503d177
Create Date: 2025-11-30 00:10:35.522564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e963e794566'
down_revision: Union[str, Sequence[str], None] = 'd9fe8503d177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
