"""cria_tabela_pesquisa_sociodemográfica

Revision ID: a353620c9826
Revises: d9fe8503d177
Create Date: 2025-11-19 22:38:15.707363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a353620c9826'
down_revision: Union[str, Sequence[str], None] = 'd9fe8503d177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pesquisa_sociodemografica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('genero', sa.Enum('Homem', 'Mulher', 'Outro', 'Prefiro_nao_responder', name='generoenum'), nullable=False),
    sa.Column('raca', sa.Enum('Branco', 'Amarelo', 'Indigena', 'Pardo', 'Preto', name='racaenum'), nullable=False),
    sa.Column('estado_civil', sa.Enum('Solteiro', 'Casado', 'Uniao_Estavel', 'Divorciado', 'Viuvo', name='estadocivilenum'), nullable=False),
    sa.Column('possui_filhos', sa.Boolean(), nullable=False),
    sa.Column('quantidade_filhos', sa.Integer(), nullable=True),
    sa.Column('tempo_empresa_meses', sa.Integer(), nullable=False),
    sa.Column('tempo_cargo_meses', sa.Integer(), nullable=False),
    sa.Column('escolaridade', sa.Enum('Fundamental_incompleto', 'Fundamental_completo', 'Medio_incompleto', 'Medio_completo', 'Superior_incompleto', 'Superior_completo', 'Pos_graduacao', 'Mestrado', 'Doutorado', name='escolaridadeenum'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pesquisa_sociodemografica_id'), 'pesquisa_sociodemografica', ['id'], unique=False)
    op.create_index(op.f('ix_pesquisa_sociodemografica_usuario_id'), 'pesquisa_sociodemografica', ['usuario_id'], unique=False)
    op.alter_column('usuarios', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuarios', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuarios', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('usuarios', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usuarios', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('usuarios', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuarios', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_pesquisa_sociodemografica_usuario_id'), table_name='pesquisa_sociodemografica')
    op.drop_index(op.f('ix_pesquisa_sociodemografica_id'), table_name='pesquisa_sociodemografica')
    op.drop_table('pesquisa_sociodemografica')
    # ### end Alembic commands ###
