"""Adiciona colunas empresa e cargo na tabela user

Revision ID: ad1b7281bd54
Revises: 45b1d490ac3b
Create Date: 2025-11-09 01:56:02.478320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad1b7281bd54'
down_revision: Union[str, Sequence[str], None] = '45b1d490ac3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('empresa', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('cargo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'cargo')
    op.drop_column('usuarios', 'empresa')
    # ### end Alembic commands ###
