"""Muda para Likert scale e remove tabela OpcoesDeResposta

Revision ID: d9fe8503d177
Revises: 9caa4c12924b
Create Date: 2025-11-11 14:22:25.905628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9fe8503d177'
down_revision: Union[str, Sequence[str], None] = '9caa4c12924b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
