"""adiciona models do forms

Revision ID: e6461ea630f3
Revises: 43566a550cf9
Create Date: 2025-11-11 13:40:04.737695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6461ea630f3'
down_revision: Union[str, Sequence[str], None] = '43566a550cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opcoes_de_resposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pergunta_id'], ['perguntas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opcoes_de_resposta_id'), 'opcoes_de_resposta', ['id'], unique=False)
    op.create_table('respostas_do_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pergunta_id', sa.Integer(), nullable=True),
    sa.Column('opcao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opcao_id'], ['opcoes_de_resposta.id'], ),
    sa.ForeignKeyConstraint(['pergunta_id'], ['perguntas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pergunta_id', name='_user_pergunta_uc')
    )
    op.create_index(op.f('ix_respostas_do_usuario_id'), 'respostas_do_usuario', ['id'], unique=False)
    op.drop_index('ix_respostas_id', table_name='respostas')
    op.drop_table('respostas')
    op.add_column('perguntas', sa.Column('tema', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perguntas', 'tema')
    op.create_table('respostas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pergunta_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('votos', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pergunta_id'], ['perguntas.id'], name='respostas_pergunta_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='respostas_pkey')
    )
    op.create_index('ix_respostas_id', 'respostas', ['id'], unique=False)
    op.drop_index(op.f('ix_respostas_do_usuario_id'), table_name='respostas_do_usuario')
    op.drop_table('respostas_do_usuario')
    op.drop_index(op.f('ix_opcoes_de_resposta_id'), table_name='opcoes_de_resposta')
    op.drop_table('opcoes_de_resposta')
    # ### end Alembic commands ###
